# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    # branches: [ "master" ]
    branches-ignore:
      - 'develop'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
        # 6.0.x
        # 7.0.x  
    - name: Build and Restore dependencies
      run: dotnet build -c Release Src/SmtpServer.sln
    - name: Test
      run: dotnet test -c Release  Src/SmtpServer.Tests/SmtpServer.Tests.csproj --no-build --verbosity normal

